Repository hypering/AH-Algorithm-Helper-Project, pull requests merged in 2020-12, with the labels that each got.

#8 [style] Calendar style 적용
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/style.js
  fe/src/components/MainContainer/Main/Calendar/index.jsx
Labels: Development, FE, PR, UI

#7 [feat] Picker Component 생성
  fe/src/components/MainContainer/Main/Picker/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Category/style.js
  fe/src/components/MainContainer/Main/Picker/Difficulty/index.jsx
  fe/src/components/MainContainer/Main/Picker/Difficulty/style.js
  fe/src/components/MainContainer/Main/Picker/Member/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/style.js
  fe/src/components/MainContainer/Main/Picker/ProblemCount/index.jsx
  fe/src/components/MainContainer/Main/Picker/ProblemCount/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/Picker/style.js
Labels: Development, FE, PR, UI

#9 Fe/refactor/style
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  be/app.js
  fe/src/components/Footer/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/style.js
  fe/src/components/MainContainer/Main/Calendar/style.js
  fe/src/components/MainContainer/Main/Picker/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Category/style.js
  fe/src/components/MainContainer/Main/Picker/Difficulty/style.js
  fe/src/components/MainContainer/Main/Picker/Member/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/style.js
  fe/src/components/MainContainer/Main/Picker/ProblemCount/index.jsx
  fe/src/components/MainContainer/Main/Picker/ProblemCount/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/Picker/style.js
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/Main/style.js
  fe/src/components/MainContainer/SideNav/index.jsx
  fe/src/components/MainContainer/SideNav/style.js
  fe/src/components/MainContainer/index.jsx
Labels: BE, Development, FE, PR, Refactor

#16 Fe/feature/picker3
  fe/src/components/MainContainer/Main/Picker/Categories/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/Category/style.js
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Difficulty/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/InputID/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/InputID/style.js
  fe/src/components/MainContainer/Main/Picker/Member/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/style.js
  fe/src/components/MainContainer/Main/Picker/ProblemCount/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
Labels: Development, FE, PR, Refactor, UI

#12 서버쪽 환경설정 및 Contest 조회 API 작성
  .gitignore
  be/.eslintrc.js
  be/.prettierrc
  be/app.js
  be/models/contest.js
  be/models/index.js
  be/models/problem.js
  be/package-lock.json
  be/package.json
  be/providers/dbProvider.js
Labels: BE, Development, PR, Refactor

#19 커뮤니티 관련 컴포넌트 작성 및 스타일링 적용, 클라이언트와 서버쪽 연동 및 API 작성
  be/app.js
  be/models/board.js
  be/models/index.js
  be/package-lock.json
  be/package.json
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/SvgIcon/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Board/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/DetailView/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/DetailView/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Header/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Header/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/style.js
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/SideNav/index.jsx
  fe/src/reset.css
Labels: BE, Development, FE, PR, Refactor, UI

#22 [feat] 문제 생성 API 작성 및 DB 적용
  be/.example_env
  be/app.js
  be/lib/problemCreator.js
  be/models/problem.js
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
Labels: BE, Development, PR, Refactor, crawling

#23 Fe/feature/picker
  be/app.js
  fe/.eslintrc.json
  fe/package-lock.json
  fe/public/Images/Tiers/4.svg
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/Difficulty/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.css
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/style.js
  fe/src/components/MainContainer/Main/Picker/Result/index.css
  fe/src/components/MainContainer/Main/Picker/Result/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
Labels: BE, Development, FE, PR, Refactor, UI

#28 대회 일정, 커뮤니티 서버, 클라이언트 작업 완료 및 리팩토링
  be/app.js
  be/routes/contest.js
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/ContestModal/style.js
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/style.js
  fe/src/components/MainContainer/Main/Calendar/index.jsx
  fe/src/components/MainContainer/Main/Calendar/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/BoardModal/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/BoardModal/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/DetailView/style.js
Labels: BE, Development, FE, PR, Refactor, UI

#29 Picker수정,Header,Side 스타일 수정, 백엔드 커뮤니티 게시판 글쓰기 API 작성
  be/.eslintrc.js
  be/app.js
  be/models/board.js
  fe/public/Images/Tiers/26.svg
  fe/public/Images/Tiers/27.svg
  fe/public/Images/Tiers/28.svg
  fe/public/Images/Tiers/29.svg
  fe/public/Images/Tiers/30.svg
  fe/src/components/Header/style.js
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/Member/index.jsx
  fe/src/components/MainContainer/Main/Picker/Member/style.js
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/style.js
  fe/src/components/MainContainer/Main/Picker/Result/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/SideNav/index.jsx
Labels: BE, Development, FE, PR, Refactor, UI

#34 [BE] 대회 일정 가져오기 API 수정
  be/app.js
  be/routes/contest.js
Labels: BE, Development, Refactor

#35 글쓰기 페이지 추가 및 라우터 추가
  fe/src/components/MainContainer/Main/Board/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/SvgIcon/style.js
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/style.js
  fe/src/components/MainContainer/Main/Board/BoardModal/index.jsx
  fe/src/components/MainContainer/Main/Board/BoardModal/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/style.js
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/style.js
  fe/src/components/MainContainer/Main/Buttons/Execute.jsx
  fe/src/components/MainContainer/Main/Buttons/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/SideNav/index.jsx
  fe/src/components/MainContainer/SideNav/style.js
  fe/src/components/MainContainer/index.jsx
Labels: Development, FE, PR, UI

#40 대회 일정 실시간 타이머 적용 및 스타일링, 리팩토링 작업
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/style.js
  fe/src/components/MainContainer/Main/Calendar/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/SvgIcon/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/Post/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Board/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Board/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/BoardModal/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/BoardModal/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/DetailView/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/DetailView/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/Header/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/Header/style.js
  fe/src/components/MainContainer/Main/NoticeBoard/index.jsx
  fe/src/components/MainContainer/Main/NoticeBoard/style.js
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/SideNav/index.jsx
  fe/src/components/MainContainer/index.jsx
  fe/src/hooks/onChangeHook.js
  fe/src/index.js
  fe/src/lib/getTimer.js
Labels: Development, FE, PR, Refactor, UI

#42 폴더 구조 리팩토링 및 필요없는 파일 삭제
  be/app.js
  be/routes/board.js
  be/routes/problem.js
  fe/README.md
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
Labels: BE, Refactor

#47 Fe
  be/app.js
  fe/src/components/MainContainer/Main/Board/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
Labels: Development
