Repository hypering/AH-Algorithm-Helper-Project, pull requests merged in 2021-01, with the labels that each got.

#49 대회 일정 관련 작업 완료 및 리팩토링
  be/app.js
  be/package-lock.json
  be/routes/board.js
  be/routes/contest.js
  fe/.eslintrc.json
  fe/babel.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/style.js
  fe/src/components/MainContainer/Main/Calendar/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/hooks/useGetContestData.js
  fe/webpack.config.js
Labels: BE, Development, FE, PR, Refactor, UI

#52 [FE]조회수 버그 수정, 검색 기능 추가 및 아이콘 변경
  be/models/board.js
  be/routes/board.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/style.js
  fe/src/components/MainContainer/Main/Board/Search/index.jsx
  fe/src/components/MainContainer/Main/Board/Search/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
Labels: BE, Development, FE, PR, Refactor, UI

#54 댓글 등록 API 작성 및 댓글 작성 컴포넌트 생성
  be/routes/board.js
  be/routes/contest.js
  fe/.eslintrc.json
  fe/package-lock.json
  fe/package.json
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/webpack.config.js
Labels: API, BE, Development, FE, PR, Refactor, UI

#55 [FE][BE] ip를 통한 중복 증가 방지 및 기타 수정사항
  be/app.js
  be/models/board.js
  be/routes/board.js
  be/routes/getip.js
  fe/package-lock.json
  fe/src/App.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/Search/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/index.jsx
Labels: API, BE, Development, FE, PR

#56 이미지 업로드를위한 Object Storage 사용 그에 따른 이미지 경로 수정 등
  .gitignore
  be/package-lock.json
  be/package.json
  be/routes/board.js
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
Labels: API, BE, Development, FE, PR

#57 댓글 실시간 업데이트 및 삭제 API 작성 및 이벤트 처리 및 리팩토링
  be/routes/board.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
Labels: API, BE, Development, FE, PR, Refactor

#58 이미지 경로 문제 수정 및 코드 리팩토링 및 애니메이션 적용
  be/.eslintrc.js
  be/lib/imageUpload.js
  be/routes/board.js
  be/routes/contest.js
  fe/src/components/Header/style.js
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/style.js
  fe/src/components/MainContainer/Main/Picker/style.js
Labels: PR, Refactor, UI

#61 글쓰기 제출시 유효성검사 페이지 작아질때 글씨들 뭉개짐 완화
  fe/src/components/Header/style.js
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/Header/style.js
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/ProblemCount/style.js
  fe/src/components/MainContainer/Main/Picker/Result/style.js
Labels: Development, FE, PR, UI

#63 스크롤바 스타일링 적용 및 유저 관련 스키마, API 작성
  be/app.js
  be/lib/validation.js
  be/models/index.js
  be/models/user.js
  be/package-lock.json
  be/package.json
  be/routes/user.js
  fe/src/components/MainContainer/Main/Board/Board/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
Labels: API, BE, Development, PR

#65 Fix/cookie
  be/app.js
  be/routes/user.js
  fe/src/App.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/hooks/useGetContestData.js
Labels: PR, Refactor

#67 Feat/oauth
  .gitignore
  be/routes/contest.js
  fe/package-lock.json
  fe/package.json
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Login/LoginButton/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/index.jsx
  fe/webpack.config.js
Labels: API, BE, Development, FE, PR, Refactor, UI

#68 useContextAPI ,useReducer 사용 로그인 상태 전역적 관리 및 기타 수정
  fe/src/App.jsx
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
Labels: Development, FE, PR, Refactor

#70 OAuth를 사용해 GitHub로그인 구현 및 리팩토링 진행
  be/package-lock.json
  be/package.json
  be/routes/user.js
  fe/package.json
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Callback/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/webpack.config.js
Labels: API, BE, Development, FE, PR, Refactor

#74 댓글의 key값을 db상의 objectId값으로 변경,가입 기능 추가 및 기타 변경사항
  be/models/board.js
  be/models/index.js
  be/routes/board.js
  be/routes/user.js
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
Labels: BE, Bug, DB, Development, FE, PR, Refactor, UI

#81 가입하기 버튼 추가, 개인 프로필 추가, 댓글에 프로필 사진 추가, 스타일링 등등
  be/models/user.js
  be/routes/board.js
  be/routes/user.js
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Login/LoginButton/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/reset.css
Labels: API, BE, Bug, DB, Development, FE, PR, Refactor, UI

#79 클라이언트 및 서버쪽 배포 환경설정 구축 및 리팩토링 진행
  be/.example_env
  be/app.js
  be/routes/board.js
  be/routes/user.js
  fe/.example_env
  fe/src/App.jsx
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Callback/index.jsx
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/hooks/useGetContestData.js
  fe/webpack.config.js
Labels: Bug, PR, Production, Refactor

#83 [Refactor] 웹 크기를 줄이거나 늘리더라도 컴포넌트 크기가 변하지 않도록 수정 및 리팩토링
  be/app.js
  fe/public/Images/logo.JPG
  fe/src/components/Footer/style.js
  fe/src/components/Header/index.jsx
  fe/src/components/Header/style.js
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Board/style.js
  fe/src/components/MainContainer/Main/Calendar/style.js
  fe/src/components/MainContainer/Main/Login/index.jsx
  fe/src/components/MainContainer/Main/Picker/style.js
  fe/src/components/MainContainer/SideNav/style.js
  fe/src/reset.css
Labels: Bug, PR, Production, Refactor, UI

#87 게시글 모달 컴포넌트 추가, 버그 수정, 스타일링 등
  be/models/user.js
  be/routes/board.js
  fe/src/components/Header/index.jsx
  fe/src/components/Header/style.js
  fe/src/components/MainContainer/Main/Account/Edit/index.jsx
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/Board/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/Header/style.js
  fe/src/components/MainContainer/Main/Board/PostModal/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/style.js
  fe/src/components/MainContainer/Main/Calendar/style.js
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/SideNav/style.js
  fe/src/components/MainContainer/index.jsx
  fe/src/hooks/checkAuth.js
  fe/src/reset.css
Labels: API, BE, Bug, DB, Development, FE, PR, Production, Refactor, UI

#86 서버 및 클라이언트 4000번 포트로 배포할 수 있도록 수정
  be/app.js
  be/routes/board.js
  be/routes/user.js
  fe/public/Images/logo.JPG
  fe/public/Images/logo.ico
  fe/public/index.html
  fe/webpack.config.js
Labels: PR, Production, Refactor

#91 무한 스크롤 적용 및 리팩토링 진행
  be/routes/board.js
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Picker/Difficulty/index.jsx
Labels: API, BE, Bug, Development, FE, PR, Refactor, UI

#92 글 삭제 기능 추가,이미지 캐시 문제 해결,NavLink 사용, 썸네일 기능 추가,기타 스타일링 등
  be/lib/profileUpload.js
  be/routes/board.js
  be/routes/user.js
  fe/src/App.jsx
  fe/src/components/Footer/style.js
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Account/Edit/index.jsx
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/PostModal/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/style.js
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Difficulty/style.js
  fe/src/components/MainContainer/Main/Picker/ProblemCount/style.js
  fe/src/components/MainContainer/Main/Picker/Result/style.js
  fe/src/components/MainContainer/SideNav/index.jsx
  fe/src/components/MainContainer/SideNav/style.js
  fe/src/components/MainContainer/index.jsx
  fe/src/hooks/checkAuth.js
  fe/src/hooks/loadLoginInfo.js
  fe/webpack.config.js
Labels: API, BE, Bug, DB, Development, FE, PR, Production, Refactor, UI

#96 [feat] 커뮤니티 게시글에 생성날짜가 표시되도록 구현
  be/lib/refinePostDatas.js
  be/models/board.js
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
Labels: API, BE, Development, FE, Refactor, UI

#95 해쉬태그 검색 기능 오류 수정, 댓글작성 컴포넌트 고정, 게시글 이미지 비율 및 크기 조정, 댓글작성시 스크롤 자동 내림 기능 추가
  be/routes/board.js
  be/routes/user.js
  fe/src/components/MainContainer/Main/Board/Board/Post/style.js
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/PostModal/index.jsx
  fe/webpack.config.js
Labels: API, BE, Bug, DB, Development, FE, PR, Refactor, UI

#98 백엔드 코드 리팩토링 진행
  be/.eslintrc.js
  be/app.js
  be/lib/imageUpload.js
  be/lib/profileUpload.js
  be/lib/refinePostDatas.js
  be/routes/board.js
  be/routes/contest.js
  be/routes/problem.js
  be/routes/user.js
  be/services/board.js
  be/services/contest.js
  be/services/problem.js
  be/services/user.js
Labels: BE, Development, PR, Refactor

#99 [refactor]FE리팩토링
  fe/src/App.jsx
  fe/src/components/Footer/index.jsx
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Account/Edit/index.jsx
  fe/src/components/MainContainer/Main/Account/Edit/style.js
  fe/src/components/MainContainer/Main/Account/Login/Callback/index.jsx
  fe/src/components/MainContainer/Main/Account/Login/LoginButton/index.jsx
  fe/src/components/MainContainer/Main/Account/Login/index.jsx
  fe/src/components/MainContainer/Main/Account/Login/style.js
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Account/Profile/style.js
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/style.js
  fe/src/components/MainContainer/Main/Board/Board/Post/SvgIcon/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/BoardModal/index.jsx
  fe/src/components/MainContainer/Main/Board/BoardModal/style.js
  fe/src/components/MainContainer/Main/Board/PostModal/index.jsx
  fe/src/components/MainContainer/Main/Board/PostModal/style.js
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Buttons/Execute.jsx
  fe/src/components/MainContainer/Main/Buttons/style.js
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Calendar/Item/index.jsx
  fe/src/components/MainContainer/Main/Calendar/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/style.js
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/Picker/style.js
  fe/src/components/MainContainer/Main/Search/index.jsx
  fe/src/components/MainContainer/Main/Search/style.js
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/components/MainContainer/index.jsx
  fe/webpack.config.js
Labels: FE, Refactor

#100 API 관련 리팩토링 진행
  be/routes/board.js
  be/routes/getip.js
  be/routes/user.js
  fe/src/App.jsx
  fe/src/components/Header/index.jsx
  fe/src/components/MainContainer/Main/Account/Edit/index.jsx
  fe/src/components/MainContainer/Main/Account/Login/index.jsx
  fe/src/components/MainContainer/Main/Account/Profile/index.jsx
  fe/src/components/MainContainer/Main/Account/SignUp/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/Post/index.jsx
  fe/src/components/MainContainer/Main/Board/Board/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/Write/index.jsx
  fe/src/components/MainContainer/Main/Board/index.jsx
  fe/src/components/MainContainer/Main/Calendar/ContestModal/index.jsx
  fe/src/components/MainContainer/Main/Picker/index.jsx
  fe/src/components/MainContainer/Main/Search/index.jsx
  fe/src/components/MainContainer/index.jsx
  fe/src/hooks/checkAuth.js
  fe/src/hooks/loadLoginInfo.js
  fe/src/hooks/useGetContestData.js
  fe/src/lib/api.js
Labels: API, Development, FE, PR, Refactor
