Repository hypering/AH-Algorithm-Helper-Project, pull requests merged in 2021-02, with the labels that each got.

#104 리팩토링, 예외처리 수정, 스타일링 수정
  be/routes/board.js
  be/routes/user.js
  be/services/board.js
  fe/src/components/MainContainer/Buttons/ExitButton/index.jsx
  fe/src/components/MainContainer/Buttons/ExitButton/style.js
  fe/src/components/MainContainer/Buttons/LoginButton/index.jsx
  fe/src/components/MainContainer/Buttons/PostDeleteButton/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
  fe/src/components/MainContainer/Main/Board/DetailView/style.js
  fe/src/components/MainContainer/Main/Board/Header/index.jsx
  fe/src/components/MainContainer/Main/Board/PostModal/index.jsx
  fe/src/components/MainContainer/Main/Board/SearchBar/index.jsx
  fe/src/components/MainContainer/Main/Board/SearchBar/style.js
  fe/src/components/MainContainer/Main/Picker/Categories/Category/index.jsx
  fe/src/components/MainContainer/Main/Picker/Categories/index.jsx
  fe/src/components/MainContainer/Main/Picker/Difficulty/index.jsx
  fe/src/components/MainContainer/Main/Picker/ProblemCount/index.jsx
  fe/src/components/MainContainer/Main/Picker/Result/index.jsx
  fe/src/components/MainContainer/Main/Search/index.jsx
  fe/src/components/MainContainer/Main/index.jsx
  fe/src/lib/api.js
  fe/src/pages/Account/Edit/index.jsx
  fe/src/pages/Account/Edit/style.js
  fe/src/pages/Account/Login/Callback/index.jsx
  fe/src/pages/Account/Login/index.jsx
  fe/src/pages/Account/Login/style.js
  fe/src/pages/Account/Profile/index.jsx
  fe/src/pages/Account/Profile/style.js
  fe/src/pages/Account/SignUp/index.jsx
  fe/src/pages/Account/SignUp/style.js
  fe/src/pages/Calendar/index.jsx
  fe/src/pages/Calendar/style.js
  fe/src/pages/FreeBoard/index.jsx
  fe/src/pages/FreeBoard/style.js
  fe/src/pages/Picker/index.jsx
  fe/src/pages/Picker/style.js
  fe/src/pages/Search/index.jsx
  fe/src/pages/Search/style.js
  fe/src/pages/Write/index.jsx
  fe/src/pages/Write/style.js
  fe/src/pages/index.jsx
Labels: BE, Bug, FE, PR, Refactor

#106 [style]스타일 수정
  fe/src/components/MainContainer/Main/Board/Header/style.js
  fe/src/components/MainContainer/Main/Board/PostModal/style.js
  fe/src/pages/Write/index.jsx
Labels: UI

#107 백엔드쪽 잘못된 코드 수정
  be/routes/user.js
Labels: Refactor

#109 하트 관련 문제점 해결
  fe/src/components/MainContainer/Main/Board/DetailView/index.jsx
Labels: Development

#111 Refactor/be
  be/services/board.js
  be/services/user.js
  fe/src/pages/Account/Edit/style.js
  fe/src/pages/Account/Profile/style.js
  fe/src/pages/Calendar/style.js
  fe/src/pages/FreeBoard/style.js
  fe/src/pages/Picker/style.js
  fe/src/pages/Search/style.js
  fe/src/pages/Write/style.js
Labels: Development, Refactor, UI

#113 문제 데이터 삽입 및 문제 데이터 삭제 API 작성 및 카테고리 관련 수정 작업 진행
  be/ecosystem.config.js
  be/package-lock.json
  be/package.json
  be/routes/problem.js
  be/services/problem.js
  fe/src/components/MainContainer/Main/Picker/Categories/Category/index.jsx
  fe/webpack.config.js
Labels: API, BE, Bug, Development, FE, PR, Refactor

#114 무중단 배포 확인 PR
  fe/webpack.config.js
Labels: PR, Production

#115 배포 작업 수정
  .github/workflows/main.yml
  be/package.json
Labels: PR, Production, Refactor

#116 [fix] 티어 이미지 수정
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
Labels: Bug, PR

#117 [fix]웹팩 이미지 관련 문제 해결 테스트
  fe/public/Images/Tiers/hi.png
  fe/public/index.html
  fe/src/Images/Tiers/1.svg
  fe/src/Images/Tiers/10.svg
  fe/src/Images/Tiers/11.svg
  fe/src/Images/Tiers/12.svg
  fe/src/Images/Tiers/13.svg
  fe/src/Images/Tiers/14.svg
  fe/src/Images/Tiers/15.svg
  fe/src/Images/Tiers/16.svg
  fe/src/Images/Tiers/17.svg
  fe/src/Images/Tiers/18.svg
  fe/src/Images/Tiers/19.svg
  fe/src/Images/Tiers/2.svg
  fe/src/Images/Tiers/20.svg
  fe/src/Images/Tiers/21.svg
  fe/src/Images/Tiers/22.svg
  fe/src/Images/Tiers/23.svg
  fe/src/Images/Tiers/24.svg
  fe/src/Images/Tiers/25.svg
  fe/src/Images/Tiers/26.svg
  fe/src/Images/Tiers/27.svg
  fe/src/Images/Tiers/28.svg
  fe/src/Images/Tiers/29.svg
  fe/src/Images/Tiers/3.svg
  fe/src/Images/Tiers/30.svg
  fe/src/Images/Tiers/4.svg
  fe/src/Images/Tiers/5.svg
  fe/src/Images/Tiers/6.svg
  fe/src/Images/Tiers/7.svg
  fe/src/Images/Tiers/8.svg
  fe/src/Images/Tiers/9.svg
  fe/src/Images/logo.ico
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/webpack.config.js
Labels: Bug, FE

#118 [fix]웹팩 이미지 관련 에러 수정 테스트
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/webpack.config.js
Labels: Bug, FE, PR

#119 [fix]웹팩 이미지 경로 오류 수정
  fe/src/components/MainContainer/Main/Picker/Result/ResEntity/index.jsx
  fe/webpack.config.js
Labels: Bug, Development, FE, PR

#120 [feat]ID 정규식 및 유효성 검사 추가
  fe/src/pages/Account/SignUp/index.jsx
Labels: Development, FE
